version: '3.8'

services:
  prod:
    build:
      context: .
      target: prod
    volumes:
      - static_volume:/usr/src/clist/staticfiles/
      - media_volume:/usr/src/clist/mediafiles/
    depends_on:
      - db
      - cache
      - nginx
    secrets:
      - db_conf
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/clist/
      - ./static:/usr/src/clist/staticfiles/
    depends_on:
      - db
      - nginx
    secrets:
      - db_conf
  cache:
    image: memcached
  legacy:
    build: ./legacy
    volumes:
      - ./legacy:/usr/src/legacy/
    depends_on:
      - db
      - nginx
    secrets:
      - db_conf
  db:
    image: postgres:14.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/mediafiles/
      - ./legacy:/usr/src/legacy/
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - certbot_www:/var/www/certbot/
      - certbot_conf:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot/
      - certbot_conf:/etc/letsencrypt/
    depends_on:
      - nginx

secrets:
  db_conf:
    file: ./.env.db


volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot_www:
  certbot_conf:
