version: '3.8'

services:
  web:
    build: .
    volumes:
      - shared_socket:/sharedsocket/
      - static_volume:/usr/src/clist/staticfiles/
      - media_volume:/usr/src/clist/mediafiles/
      - .:/usr/src/clist/
    depends_on:
      - db
      - cache
    secrets:
      - env
  cache:
    image: memcached
  legacy:
    build: ./legacy
    volumes:
      - shared_socket:/sharedsocket/
      - ./legacy:/usr/src/legacy/
    depends_on:
      - db
    secrets:
      - env
  db:
    image: postgres:14.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  nginx:
    image: nginx:alpine
    volumes:
      - shared_socket:/sharedsocket/
      - static_volume:/staticfiles/
      - media_volume:/mediafiles/
      - ./legacy:/usr/src/legacy/
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - certbot_www:/var/www/certbot/
      - certbot_conf:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - legacy
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot/
      - certbot_conf:/etc/letsencrypt/

secrets:
  env:
    file: ./.env.prod


volumes:
  postgres_data:
  shared_socket:
  static_volume:
  media_volume:
  certbot_www:
  certbot_conf:
