version: '3.8'

services:
  web:
    build: .
    volumes:
      - shared_socket:/sharedsocket/
      - static_volume:/usr/src/clist/staticfiles/
      - media_volume:/usr/src/clist/mediafiles/
      - .:/usr/src/clist/
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - cache
  cache:
    image: memcached
  legacy:
    build: ./legacy
    volumes:
      - shared_socket:/sharedsocket/
      - ./legacy:/usr/src/legacy/
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:14.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - shared_socket:/sharedsocket/
      - static_volume:/staticfiles/
      - media_volume:/mediafiles/
      - ./legacy:/usr/src/legacy/
    ports:
      - 58042:80
      - 58043:81
      - 80:80
    depends_on:
      - web


volumes:
  postgres_data:
  shared_socket:
  static_volume:
  media_volume:
