version: '3.8'

services:
  prod:
    build:
      context: .
      target: prod
    volumes:
      - static_volume:/usr/src/clist/staticfiles/
      - media_volume:/usr/src/clist/mediafiles/
      - ./logs/production:/usr/src/clist/logs/
      - ./legacy/logs/:/usr/src/clist/logs/legacy/
    depends_on:
      - db
      - cache
    secrets:
      - db_conf
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./src/:/usr/src/clist/
      - ./legacy/api/:/usr/src/clist/legacy/api/
      - ./src/static:/usr/src/clist/staticfiles/
      - media_volume:/usr/src/clist/mediafiles/
      - ./logs/development:/usr/src/clist/logs/
      - ./legacy/logs/:/usr/src/clist/logs/legacy/
    depends_on:
      - db
    secrets:
      - db_conf
    ports:
      - ${CLIST_DEV_PORT:-10042}:10042
  cache:
    image: memcached
  legacy:
    build: ./legacy
    volumes:
      - ./legacy:/usr/src/legacy/
    depends_on:
      - db
    secrets:
      - db_conf
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - ./.env.db
    depends_on:
      - db
    ports:
      - 5050:80
  db:
    image: postgres:14.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    command: >
      postgres
      -c max_connections=50
      -c shared_buffers=1GB
      -c work_mem=20MB
      -c maintenance_work_mem=200MB
      -c effective_cache_size=2GB
      -c checkpoint_timeout=30min
      -c max_wal_size=4GB
      -c min_wal_size=320MB
      -c bgwriter_delay=20
  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/mediafiles/
      - ./legacy:/usr/src/legacy/
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - certbot_www:/var/www/certbot/
      - certbot_conf:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./logs/letsencrypt:/var/log/letsencrypt
      - certbot_www:/var/www/certbot/
      - certbot_conf:/etc/letsencrypt/
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 1d & wait $${!}; done;'"

secrets:
  db_conf:
    file: ./.env.db

volumes:
  postgres_data:
  pgadmin_data:
  static_volume:
  media_volume:
  certbot_www:
  certbot_conf:
